### ISSUE TITLE
Plots are covered by legend and are hard to read

### ISSUE THREAD

**Issue by pavpanchekha** [mwillsey/crossbot#3]
The plot is hard to read, and the legend covers half the plot.

- [ ] Switch from line to dot plot. The lines are meaningless and confusing
- [ ] Move legend away from plot area
- [ ] Widen plot to fit more days

**Comment by mwillsey** [comment]
- I like the line plot more than dot, it makes it easier to follow your progress
- The legend is dynamically placed to cover up the "least important" part of the graph. Check the previous plots to see how it moves around. Also, the legend is large because of the low plot resolution.
- Slack will only show [thumbnails](https://api.slack.com/docs/message-attachments#image_url) 400px wide.
